language: python

python:
  - 3.5.1

cache: pip

install:
  - CACHE_DIR="$HOME/.cache/pip"
  - pip install coveralls --cache-dir=$CACHE_DIR
  - pip install -r etc/requirements.txt --cache-dir=$CACHE_DIR

script:
  - coverage run coverage run --source=pykdb setup.py test

after_success:
  - coveralls
